import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#131313]`}
      >
        <main>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
